# Generated by Django 5.2.14 on 2026-05-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_attribute_attributevalue_productvariat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariat',
            new_name='ProductVariant',
        ),
    ]
